@include('backend.fixed_asset.partials.errors')
<div class="row">
    <div class="col-md-8 mb-3"><label>Asset Name *</label><input type="text" name="asset_name" class="form-control" value="{{ old('asset_name', $asset->asset_name ?? '') }}" required></div>
    <div class="col-md-4 mb-3"><label>Serial Number</label><input type="text" name="serial_number" class="form-control" value="{{ old('serial_number', $asset->serial_number ?? '') }}"></div>
    <div class="col-md-4 mb-3"><label>Category *</label><select name="category_id" class="form-control" required><option value="">Select</option>@foreach($categories as $category)<option value="{{ $category->id }}" {{ old('category_id', $asset->category_id ?? '') == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>@endforeach</select></div>
    <div class="col-md-4 mb-3"><label>Warehouse *</label><select name="warehouse_id" class="form-control" required><option value="">Select warehouse</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" {{ old('warehouse_id', $asset->warehouse_id ?? '') == $warehouse->id ? 'selected' : '' }}>{{ $warehouse->title }}</option>@endforeach</select><small class="text-muted">Warehouse is mandatory and works as asset branch/base.</small></div>
    <div class="col-md-4 mb-3"><label>Location / Room</label><select name="location_id" class="form-control"><option value="">Select</option>@foreach($locations as $location)<option value="{{ $location->id }}" {{ old('location_id', $asset->location_id ?? '') == $location->id ? 'selected' : '' }}>{{ $location->name }}</option>@endforeach</select></div>
    <div class="col-md-4 mb-3"><label>Brand</label><input type="text" name="brand_name" class="form-control" value="{{ old('brand_name', $asset->brand_name ?? '') }}"></div>
    <div class="col-md-4 mb-3"><label>Model</label><input type="text" name="model_name" class="form-control" value="{{ old('model_name', $asset->model_name ?? '') }}"></div>
    <div class="col-md-4 mb-3"><label>Condition *</label><select name="condition_status" class="form-control" required>@foreach(['new','excellent','good','fair','poor','damaged','beyond_repair'] as $s)<option value="{{ $s }}" {{ old('condition_status', $asset->condition_status ?? 'good') == $s ? 'selected' : '' }}>{{ ucwords(str_replace('_',' ', $s)) }}</option>@endforeach</select></div>
    <div class="col-md-3 mb-3"><label>Purchase Date</label><input type="date" name="purchase_date" class="form-control" value="{{ old('purchase_date', isset($asset) && $asset->purchase_date ? $asset->purchase_date->format('Y-m-d') : '') }}"></div>
    <div class="col-md-3 mb-3"><label>Available For Use</label><input type="date" name="available_for_use_date" class="form-control" value="{{ old('available_for_use_date', isset($asset) && $asset->available_for_use_date ? $asset->available_for_use_date->format('Y-m-d') : '') }}"></div>
    <div class="col-md-3 mb-3"><label>Purchase Cost *</label><input type="number" step="0.01" name="purchase_cost" class="form-control" value="{{ old('purchase_cost', $asset->purchase_cost ?? 0) }}" required></div>
    <div class="col-md-3 mb-3"><label>Additional Cost</label><input type="number" step="0.01" name="additional_cost" class="form-control" value="{{ old('additional_cost', $asset->additional_cost ?? 0) }}"></div>
    <div class="col-md-3 mb-3"><label>Residual Value</label><input type="number" step="0.01" name="residual_value" class="form-control" value="{{ old('residual_value', $asset->residual_value ?? 0) }}"></div>
    <div class="col-md-3 mb-3"><label>Useful Life (months)</label><input type="number" name="useful_life_months" class="form-control" value="{{ old('useful_life_months', $asset->useful_life_months ?? 36) }}"></div>
    <div class="col-md-3 mb-3"><label>Depreciation Method</label><select name="depreciation_method" class="form-control">@foreach(['straight_line','diminishing_balance','units_of_production','none'] as $m)<option value="{{ $m }}" {{ old('depreciation_method', $asset->depreciation_method ?? 'straight_line') == $m ? 'selected' : '' }}>{{ ucwords(str_replace('_',' ', $m)) }}</option>@endforeach</select></div>
    <div class="col-md-3 mb-3"><label>Invoice No</label><input type="text" name="invoice_number" class="form-control" value="{{ old('invoice_number', $asset->invoice_number ?? '') }}"></div>
    <div class="col-md-6 mb-3"><label>Warranty Start</label><input type="date" name="warranty_start_date" class="form-control" value="{{ old('warranty_start_date', isset($asset) && $asset->warranty_start_date ? $asset->warranty_start_date->format('Y-m-d') : '') }}"></div>
    <div class="col-md-6 mb-3"><label>Warranty End</label><input type="date" name="warranty_end_date" class="form-control" value="{{ old('warranty_end_date', isset($asset) && $asset->warranty_end_date ? $asset->warranty_end_date->format('Y-m-d') : '') }}"></div>
    <div class="col-md-12 mb-3"><label>Description / Notes</label><textarea name="description" class="form-control" rows="3">{{ old('description', $asset->description ?? '') }}</textarea></div>
</div>
<button class="btn btn-primary">Save Asset</button>
<a href="{{ route('fixed-assets.assets.index') }}" class="btn btn-light">Cancel</a>
