@extends('backend.master')
@section('page_title','Commission Settlement Details')
@section('page_heading','Commission Settlement Details')
@section('content')
<div class="card"><div class="card-body"><div class="d-flex justify-content-between mb-3"><h4>{{ $settlement->settlement_no }}</h4><div><button onclick="window.print()" class="btn btn-light btn-sm">Print</button><a href="{{ route('sr.commission-settlements.index') }}" class="btn btn-secondary btn-sm">Back</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<table class="table table-bordered"><tr><th>For</th><td>{{ ucfirst($settlement->settlement_for) }}</td><th>Person</th><td>{{ $settlement->settlement_for=='salesman' ? ($settlement->user->name ?? '—') : ($settlement->affiliate->name ?? '—') }}</td></tr><tr><th>Period</th><td>{{ $settlement->period_start->format('Y-m-d') }} to {{ $settlement->period_end->format('Y-m-d') }}</td><th>Status</th><td><span class="badge badge-{{ $settlement->status=='paid'?'success':($settlement->status=='cancelled'?'danger':($settlement->status=='draft'?'warning':'info')) }}">{{ ucfirst(str_replace('_',' ',$settlement->status)) }}</span></td></tr><tr><th>Total</th><td>{{ number_format($settlement->total_commission,2) }}</td><th>Adjustment</th><td>{{ number_format($settlement->adjustment_amount,2) }}</td></tr><tr><th>Payable</th><td>{{ number_format($settlement->payable_amount,2) }}</td><th>Paid / Due</th><td>{{ number_format($settlement->paid_amount,2) }} / {{ number_format($settlement->due_amount,2) }}</td></tr><tr><th>Settled At</th><td>{{ $settlement->settled_at ? $settlement->settled_at->format('Y-m-d H:i') : '—' }}</td><th>Accounting</th><td><span class="badge badge-light">{{ ucfirst(str_replace('_',' ',$settlement->accounting_status ?? 'pending')) }}</span><br><small>Approve Txn: {{ $settlement->accounting_transaction_id ?: '—' }} | Pay Txn: {{ $settlement->payment_transaction_id ?: '—' }}</small></td></tr><tr><th>Note</th><td colspan="3">{!! nl2br(e($settlement->note)) !!}</td></tr></table>
<div class="alert alert-secondary py-2"><strong>Accounting Flow:</strong> Approval = Dr Sales Commission Expense / Cr Commission Payable. Full payment = Dr Commission Payable / Cr Cash or Bank.</div>
<div class="mb-3">
@if($settlement->status == 'draft')<form method="POST" class="d-inline" action="{{ route('sr.commission-settlements.approve',$settlement->id) }}">@csrf<button class="btn btn-primary" onclick="return confirm('Approve this settlement?')">Approve</button></form>@endif
@if(in_array($settlement->status, ['approved','partially_paid']))<form method="POST" class="d-inline-block" action="{{ route('sr.commission-settlements.mark-paid',$settlement->id) }}">@csrf <input type="number" step="0.01" name="paid_amount" class="form-control d-inline-block" style="width:160px" placeholder="Paid amount" value="{{ $settlement->due_amount }}" required> <input type="number" name="payment_method_id" class="form-control d-inline-block" style="width:150px" placeholder="Payment method ID"> <input type="text" name="note" class="form-control d-inline-block" style="width:220px" placeholder="Payment note"> <button class="btn btn-success" onclick="return confirm('Mark payment for this settlement?')">Mark Paid</button></form>@endif
@if(in_array($settlement->status, ['draft','approved']) && (float)$settlement->paid_amount <= 0)<form method="POST" class="d-inline" action="{{ route('sr.commission-settlements.cancel',$settlement->id) }}">@csrf<button class="btn btn-danger" onclick="return confirm('Cancel this settlement?')">Cancel</button></form>@endif
</div>
<h5>Items</h5><table class="table table-bordered"><thead><tr><th>Order</th><th>Commission Entry Status</th><th>Commission</th><th>Settled</th></tr></thead><tbody>@foreach($settlement->items as $item)<tr><td>{{ optional(optional($item->commissionEntry)->order)->order_code ?? '#'.optional($item->commissionEntry)->product_order_id }}</td><td>{{ optional($item->commissionEntry)->status ?? '—' }}</td><td>{{ number_format($item->commission_amount,2) }}</td><td>{{ number_format($item->settled_amount,2) }}</td></tr>@endforeach</tbody></table>
</div></div>
@endsection
