@csrf
@if(isset($asset)) @method('PUT') @endif
<div class="row">
 <div class="col-md-6 mb-3"><label class="required">Asset Name</label><input name="asset_name" class="form-control" value="{{ old('asset_name',$asset->asset_name ?? '') }}" required></div>
 <div class="col-md-3 mb-3"><label class="required">Category</label><select name="category_id" class="form-control" required><option value="">Select</option>@foreach($categories as $c)<option value="{{ $c->id }}" {{ old('category_id',$asset->category_id ?? '') == $c->id ? 'selected' : '' }}>{{ $c->name }}</option>@endforeach</select></div>
 <div class="col-md-3 mb-3"><label class="required">Warehouse / Branch</label><select name="warehouse_id" class="form-control" required><option value="">Select Warehouse</option>@foreach($warehouses as $w)<option value="{{ $w->id }}" {{ old('warehouse_id',$asset->warehouse_id ?? '') == $w->id ? 'selected' : '' }}>{{ $w->title }}</option>@endforeach</select><small class="text-danger">Mandatory for every asset.</small></div>
 <div class="col-md-3 mb-3"><label>Location</label><select name="location_id" class="form-control"><option value="">Select</option>@foreach($locations as $l)<option value="{{ $l->id }}" {{ old('location_id',$asset->location_id ?? '') == $l->id ? 'selected' : '' }}>{{ $l->name }}</option>@endforeach</select></div>
 <div class="col-md-3 mb-3"><label>Serial Number</label><input name="serial_number" class="form-control" value="{{ old('serial_number',$asset->serial_number ?? '') }}"></div>
 <div class="col-md-3 mb-3"><label>Purchase Date</label><input type="date" name="purchase_date" class="form-control" value="{{ old('purchase_date',isset($asset)&&$asset->purchase_date?$asset->purchase_date->format('Y-m-d'):'') }}"></div>
 <div class="col-md-3 mb-3"><label>Available For Use</label><input type="date" name="available_for_use_date" class="form-control" value="{{ old('available_for_use_date',isset($asset)&&$asset->available_for_use_date?$asset->available_for_use_date->format('Y-m-d'):'') }}"></div>
 <div class="col-md-3 mb-3"><label class="required">Purchase Cost</label><input type="number" step="0.01" min="0" name="purchase_cost" class="form-control" value="{{ old('purchase_cost',$asset->purchase_cost ?? 0) }}" required></div>
 <div class="col-md-3 mb-3"><label>Additional Cost</label><input type="number" step="0.01" min="0" name="additional_cost" class="form-control" value="{{ old('additional_cost',$asset->additional_cost ?? 0) }}"></div>
 <div class="col-md-3 mb-3"><label>Residual Value</label><input type="number" step="0.01" min="0" name="residual_value" class="form-control" value="{{ old('residual_value',$asset->residual_value ?? 0) }}"></div>
 <div class="col-md-3 mb-3"><label>Useful Life Months</label><input type="number" min="1" name="useful_life_months" class="form-control" value="{{ old('useful_life_months',$asset->useful_life_months ?? '') }}"></div>
 <div class="col-md-3 mb-3"><label class="required">Depreciation Method</label><select name="depreciation_method" class="form-control" required>@foreach(['straight_line','diminishing_balance','units_of_production','none'] as $s)<option value="{{ $s }}" {{ old('depreciation_method',$asset->depreciation_method ?? 'straight_line') == $s ? 'selected' : '' }}>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select></div>
 <div class="col-md-3 mb-3"><label class="required">Condition</label><select name="condition_status" class="form-control" required>@foreach(['new','excellent','good','fair','poor','damaged','beyond_repair'] as $s)<option value="{{ $s }}" {{ old('condition_status',$asset->condition_status ?? 'good') == $s ? 'selected' : '' }}>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select></div>
 <div class="col-md-3 mb-3"><label>Warranty Start</label><input type="date" name="warranty_start_date" class="form-control" value="{{ old('warranty_start_date',isset($asset)&&$asset->warranty_start_date?$asset->warranty_start_date->format('Y-m-d'):'') }}"></div>
 <div class="col-md-3 mb-3"><label>Warranty End</label><input type="date" name="warranty_end_date" class="form-control" value="{{ old('warranty_end_date',isset($asset)&&$asset->warranty_end_date?$asset->warranty_end_date->format('Y-m-d'):'') }}"></div>
</div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<button class="btn btn-primary">{{ isset($asset) ? 'Update Asset' : 'Save Asset' }}</button><a href="{{ route('fixed-assets.assets.index') }}" class="btn btn-light">Cancel</a>
