@extends('backend.master')
@section('page_title','Asset Register')
@section('page_heading','Asset Register')
@section('header_css')@include('backend.fixed_asset._style')@endsection
@section('content')
<div class="fa-page-wrap">
    @include('backend.fixed_asset.partials.nav')
<div class="card"><div class="card-body"><div class="d-flex justify-content-between mb-3"><h4 class="fa-card-title">All Fixed Assets</h4><a href="{{ route('fixed-assets.assets.create') }}" class="btn btn-fa-primary btn-sm"><i class="feather-plus"></i> Add Asset</a></div>
<form class="row mb-3" method="get"><div class="col-md-3"><input name="q" value="{{ request('q') }}" class="form-control" placeholder="Code, name, serial"></div><div class="col-md-3"><select name="warehouse_id" class="form-control"><option value="">All Warehouses</option>@foreach($warehouses as $w)<option value="{{ $w->id }}" {{ request('warehouse_id') == $w->id ? 'selected' : '' }}>{{ $w->title }}</option>@endforeach</select></div><div class="col-md-3"><select name="category_id" class="form-control"><option value="">All Categories</option>@foreach($categories as $c)<option value="{{ $c->id }}" {{ request('category_id') == $c->id ? 'selected' : '' }}>{{ $c->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="status" class="form-control"><option value="">All Status</option>@foreach(['available','assigned','in_transfer','under_maintenance','idle','lost','damaged','retired'] as $s)<option value="{{ $s }}" {{ request('status') == $s ? 'selected' : '' }}>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-dark btn-block">Filter</button></div></form>
<div class="table-responsive"><table class="table table-bordered table-hover"><thead><tr><th>Code</th><th>Name</th><th>Category</th><th>Warehouse</th><th>Cost</th><th>Book Value</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($assets as $asset)<tr><td><strong>{{ $asset->asset_code }}</strong></td><td>{{ $asset->asset_name }}<br><small class="text-muted">{{ $asset->serial_number }}</small></td><td>{{ optional($asset->category)->name }}</td><td>{{ optional($asset->warehouse)->title }}</td><td>{{ number_format($asset->capitalized_cost,2) }}</td><td>{{ number_format($asset->carrying_amount,2) }}</td><td><span class="fa-badge">{{ str_replace('_',' ',$asset->operational_status) }}</span></td><td class="fa-actions"><a class="btn btn-info btn-sm" href="{{ route('fixed-assets.assets.show',$asset) }}">View</a><a class="btn btn-warning btn-sm" href="{{ route('fixed-assets.assets.edit',$asset) }}">Edit</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted">No assets found.</td></tr>@endforelse</tbody></table></div>{{ $assets->links() }}</div></div>
</div>
@endsection
