@extends('backend.master')
@section('page_title','Asset Details')
@section('page_heading','Asset Details')
@section('header_css')@include('backend.fixed_asset._style')@endsection
@section('content')
<div class="fa-page-wrap">
    @include('backend.fixed_asset.partials.nav')
<div class="row"><div class="col-lg-8"><div class="card"><div class="card-body"><div class="d-flex justify-content-between"><h4 class="fa-card-title">{{ $asset->asset_code }} — {{ $asset->asset_name }}</h4><div><a href="{{ route('fixed-assets.assets.edit',$asset) }}" class="btn btn-warning btn-sm">Edit</a><a href="{{ route('fixed-assets.assets.tag',$asset) }}" class="btn btn-dark btn-sm">Tag</a></div></div><hr><div class="row"><div class="col-md-6"><p><b>Category:</b> {{ optional($asset->category)->name }}</p><p><b>Warehouse:</b> {{ optional($asset->warehouse)->title }}</p><p><b>Location:</b> {{ optional($asset->location)->name }}</p><p><b>Status:</b> <span class="fa-badge">{{ str_replace('_',' ',$asset->operational_status) }}</span></p></div><div class="col-md-6"><p><b>Purchase Cost:</b> {{ number_format($asset->purchase_cost,2) }}</p><p><b>Capitalized Cost:</b> {{ number_format($asset->capitalized_cost,2) }}</p><p><b>Accumulated Dep.:</b> {{ number_format($asset->accumulated_depreciation,2) }}</p><p><b>Book Value:</b> {{ number_format($asset->carrying_amount,2) }}</p></div></div><hr><div class="fa-actions"><a class="btn btn-success btn-sm" href="{{ route('fixed-assets.assignments.create',$asset) }}">Assign</a><a class="btn btn-fa-primary btn-sm" href="{{ route('fixed-assets.transfers.create',$asset) }}">Transfer</a><a class="btn btn-info btn-sm" href="{{ route('fixed-assets.maintenance.create',$asset) }}">Maintenance</a><a class="btn btn-danger btn-sm" href="{{ route('fixed-assets.disposals.create',$asset) }}">Dispose</a></div></div></div></div><div class="col-lg-4"><div class="card"><div class="card-body"><h5>Event Timeline</h5>@forelse($asset->events as $event)<div class="border-bottom py-2"><strong>{{ str_replace('_',' ',$event->event_type) }}</strong><br><small>{{ $event->created_at }} — {{ $event->note }}</small></div>@empty<div class="text-muted">No events.</div>@endforelse</div></div></div></div>
</div>
@endsection
